default_platform(:ios)

platform :ios do
  
  lane :dev do
    begin
        desc "빌드를 시작 합니다."
        build_app(
            scheme: "swiftuiTest02",
            configuration: "Debug",
            export_method: "development",
            output_directory: "./build/Debug",
            output_name: "swiftuiTest02-Debug.ipa",
            include_bitcode: false,
            clean: true
        )
    rescue => exception
      desc exception
    end
  end
  
end
